# Sử dụng base image Node.js chính thức
FROM node:18-alpine

# Thiết lập thư mục làm việc trong container
WORKDIR /usr/src/app

# Sao chép package.json và package-lock.json
COPY package*.json./

# Cài đặt các dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn còn lại
COPY..

# Expose port mà ứng dụng sẽ chạy
EXPOSE 3000

# Lệnh để khởi chạy ứng dụng
CMD [ "node", "server.js" ]
